apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cn-recap-week2
labels:
  app: redis
spec:
  clusterIP: None        # Headless
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
