apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: cn-recap-week2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values: ["ssd"]
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "frontend"
        effect: "PreferNoSchedule"
      containers:
      - name: web
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: redis-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: cn-recap-week2
spec:
  type: NodePort
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080   # 也可省略让集群分配（范围 30000-32767）
