apiVersion: v1
kind: Pod
metadata:
  name: sidecar-log-pod
spec:
  # 1. 定义一个共享的 Volume
  volumes:
  - name: shared-logs
    # emptyDir 是一个随 Pod 生命周期的临时目录
    emptyDir: {}

  containers:
  # 2. 主容器：Nginx
  - name: nginx-app
    image: nginx:1.24
    ports:
    - containerPort: 80
    # 3. 将共享 Volume 挂载到 Nginx 的日志目录
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  # 4. Sidecar 容器：日志读取器
  - name: log-sidecar
    image: busybox:1.35
    # 5. 命令它持续地读取 Nginx 的访问日志文件
    command: ["/bin/sh", "-c", "tail -f /mnt/logs/access.log"]
    # 6. 将同一个共享 Volume 挂载到自己的一个目录下
    volumeMounts:
    - name: shared-logs
      mountPath: /mnt/logs