apiVersion: v1
kind: Pod
metadata: 
  name: multi-container-demo
spec:
  containers:
  - name: nginx-main
    image: nginx:1.24
    ports:
    - containerPort: 80

  - name: busybox-sidecar
    image: busybox:1.35
    command: ['sh','-c','while true; do sleep 3600; done']