apiVersion: v1
kind: Pod
metadata:
  name: secret-usage-pod
spec:
  containers:
  - name: my-app
    image: busybox:1.35
    # 这个命令会同时打印环境变量和文件内容
    command: ["sh", "-c", "echo 'Password from ENV:' $DB_PASSWORD && echo '----' && echo 'Password from file:' && cat /etc/secrets/password && sleep 3600"]

    # --- 方式一：注入为环境变量 ---
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef: # 引用一个 Secret key
          name: db-credentials # Secret 的名字
          key: password     # Secret 中的 key

    # --- 方式二：挂载为文件 ---
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secrets" # 挂载到容器的这个路径
      readOnly: true

  # 在 Pod 层面定义 Volume
  volumes:
  - name: secret-volume
    secret: # Volume 的类型是 secret
      secretName: db-credentials # 引用名为 db-credentials 的 Secret