apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resources-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hpa
  template:
    metadata:
      labels:
        app: nginx-hpa
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
        # --- 关键部分：资源配额 ---
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
          limits:
            cpu: "400m"
            memory: "128Mi"